### ISSUE TITLE
Missing Solutions to Exercises 1.2 and 2.1

### ISSUE THREAD

**Issue by buckeyja** [vkarpov15/mastering-async-await-issues#12]
Are there a solutions to Exercise 1.2 or 2.1? It would be nice to be able to compare notes. If there aren't is there somewhere that we can share our solutions.

Thanks! 

P.S. Thanks for the book Valeri! It's been really helpful.

**Comment by vkarpov15** [comment]
I haven't published solutions for those. Maybe if I do a "answers in the back of the book" type thing?

**Comment by buckeyja** [comment]
> I haven't published solutions for those. Maybe if I do a "answers in the back of the book" type thing?

Answers in the back of the book would be great! Just something to compare against would be nice.

**Comment by vkarpov15** [comment]
Fixed. Please email me val [at] karpov.io if you want an updated copy with solutions :+1:
