### ISSUE TITLE
Never received email with link to purchase

### ISSUE THREAD

**Issue by jacklinton** [vkarpov15/mastering-async-await-issues#13]
Hello. I purchased the book yesterday through paypal from your site and the confirmation page said a copy of the book would be sent to the email I ordered with but I never received that email. I only got a receipt from paypal which didn't have any links or references to the text.

I checked in my junk mail and everywhere else I could think to look. The email I ordered it from was jacklinton@mac.com

**Comment by vkarpov15** [comment]
I sent you an email with the ebook, please let me know if you received it.
