### ISSUE TITLE
Bought Mastering Async / Await - No mail and PDF of Mastering Mongoose was made available

### ISSUE THREAD

**Issue by sid-desh** [vkarpov15/mastering-async-await-issues#17]
Hello,
I purchased Mastering Async Await and paid 29.99 USD however for me the PDF version of Mastering Mongoose was made available. Additionally, I got a message that a mail is sent with the PDF but have not received any mail (spam checked).

Please help and provide me the correct ebook.

My email id is - sidharth.r.deshpande@gmail.com

**Comment by vkarpov15** [comment]
Followed up in email, so sorry for the trouble!
