### ISSUE TITLE
epub version

### ISSUE THREAD

**Issue by vkarpov15** [vkarpov15/mastering-async-await-issues#3]
Re: https://twitter.com/EricMasiello/status/1038055915314982916

**Comment by ericmasiello** [comment]
@vkarpov15 any updates on this?

**Comment by vkarpov15** [comment]
Not yet, haven't had a chance to make any progress. I'm on it later today, thanks for your patience.

**Comment by ericmasiello** [comment]
Thank you!

**Comment by stevepsharpe** [comment]
I'd also be interested in an epub version. I'm about to purchase, but an epub is a must for me. Thanks!

**Comment by vkarpov15** [comment]
Thanks for your patience, this took a lot longer than expected because styling epubs is very tricky. But I finally managed to get an epub version that looks right on iBooks and Google Books thanks to [this excellent npm module](https://www.npmjs.com/package/epub-gen). Here it is on my Google Books

![image](https://user-images.githubusercontent.com/1620265/49046034-d37c4c00-f1a0-11e8-96c4-74b79978c67a.png)

![image](https://user-images.githubusercontent.com/1620265/49046125-16d6ba80-f1a1-11e8-9516-2573145d4e22.png)

If you want the epub, send an email to val@karpov.io with your transaction number and I'll send it to you :+1:
