### ISSUE TITLE
Example 1.12 ReferenceError thrown due to typo

### ISSUE THREAD

**Issue by gareys** [vkarpov15/mastering-async-await-issues#4]
```
async function test() {
  try {
    const bad = undefined;
    bad.x;
    const p = Promise.reject(new Error('Oops!'));
    await p;
  } catch (error) {
    // "cannot read property 'x' of undefined"
    console.log(err.message);
  }
}
```

note the console.log statement should read...

`console.log(error.message)`

Now it will throw a TypeError like you had mentioned.

**Comment by vkarpov15** [comment]
Good catch, thanks, fixed. If you want an updated copy, please send an email to val@karpov.io with your paypal transaction number so I know where to send it. Thanks again.
