### ISSUE TITLE
Chapter 2: Grammatical Error - Verb Tense

### ISSUE THREAD

**Issue by gareys** [vkarpov15/mastering-async-await-issues#5]
In this excerpt on page 18, the highlighted word `push` should be `pushes`.

> For now, then() is simple, it _**push**_ onFulfilled() and onRejected() onto an array chained.
> Then, resolve() and reject() will call them when the promise is fullled
> or rejected. If the
> promise is already settled, the then() function will queue up onFulfilled() or onRejected()
> to run on the next tick of the event loop using setImmediate().

**Comment by vkarpov15** [comment]
Thanks for reporting, I fixed this:

![image](https://user-images.githubusercontent.com/1620265/47802574-f2550300-dd06-11e8-8853-26feb4ac01ab.png)

Email your paypal transaction number to val@karpov.io if you want an updated copy, so I know where to send it :+1:
