### ISSUE TITLE
Example 3.22: Reference a more complete example instead of providing informal psuedocode

### ISSUE THREAD

**Issue by gareys** [vkarpov15/mastering-async-await-issues#6]
In example 3.22, you state that using try/catch with an async function that returns a rejected promise is not handled. Here is the excerpt:
```
async function fn1() {
 // Bad! Doesn't handle returned promise rejections and is clunky
 try { /* Complex function here */ } catch (err) { handleError(err); }
}
```

You go into detail about this in Example 3.4, but by the time I'm reading that part of the chapter, it has been overshadowed by more enlightening async/await information. A reference to the relevant material in example 3.4 as opposed to a very brief/informal example would be better here.

As a side note, I heavily use async/await with try/catch but will try to be more preventative by using `.catch` after reading your book. I don't think there is an issue with try/catch, but I think a missing `await` clause is something that could go unnoticed with a fast-paced team of developers.

**Comment by vkarpov15** [comment]
Thanks for the feedback. What do you think of the below changes?

![image](https://user-images.githubusercontent.com/1620265/47803559-292c1880-dd09-11e8-9d66-044d212cf179.png)

Re: using `try/catch`, I don't think there's a problem with using try/catch for syntactic convenience. `try/catch` is fine in business logic, but whatever architecture you use around async/await should use `.catch()` to make sure you don't end up with unhandled rejections.

**Comment by gareys** [comment]
I think that is great! Thanks for addressing the issues I brought up.  I finished your book earlier this week and I found the highlights about `.catch` and scopes with async/await most helpful. Great read!
